# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Configuração padrão para as máquinas
  config.vm.box = "ubuntu/bionic64" # Use uma box Ubuntu 18.04 como exemplo
  config.ssh.insert_key = false
  # vb.memory = "520"

  # Máquina Administradora (Control Node)
  config.vm.define "ansible_control" do |ansible_control|
    ansible_control.vm.hostname = "ansible-control"
    ansible_control.vm.network "private_network", ip: "192.168.33.10"
    ansible_control.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3-pip
      pip3 install ansible
    SHELL
  end
  # Máquina Gerenciada 1
  config.vm.define "managed_node_1" do |managed_node_1|
    managed_node_1.vm.hostname = "managed-node-1"
    managed_node_1.vm.network "private_network", ip: "192.168.33.11"
    managed_node_1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3
    SHELL
  end
  # Máquina Gerenciada 2
  config.vm.define "managed_node_2" do |managed_node_2|
    managed_node_2.vm.hostname = "managed-node-2"
    managed_node_2.vm.network "private_network", ip: "192.168.33.12"
    managed_node_2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3
    SHELL
  end
end